spring:
  application:
    name: "SpringSecurity"
  devtools:
    restart:
      enabled: true
  main:
    banner-mode: off
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  ssl:
    key-store: ${SSL_KEYSTORE}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: ${SSL_KEYSTORE_TYPE}
    key-alias: ${SSL_KEY_ALIAS}
    key-password: ${SSL_KEY_PASSWORD}
  port: ${SERVER_PORT}

auth:
  value: ${AUTH_KEY}